### PR TITLE
Just reviewing code 😁

### PR DESCRIPTION
**Pull request by chhetri123**

### CODE REVIEW

**Review by Nirajan17 — COMMENTED** [review]
Mero linked list wala code hererw kaha wrong xa vandeu ta 
data herne belama first node ko bahek dekhaunna

**Comment by chhetri123** [comment]
> Mero linked list wala code hererw kaha wrong xa vandeu ta data herne belama first node ko bahek dekhaunna

arko pull request ma hera hai 😂

**Comment by Nirajan17** [comment]
Hahahaha
College jannau??

**Comment by Nirajan17** [comment]
Aaile vanamla hai
Khana kahdai xu

**Pull request closed without merging**
